name: Create and Push Docker Image

on:
  push:
    tags:
    - '**'
    branches:
    - "**"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: strangelove-ventures/heighliner-build-action@v0.0.3
        with:
          github-organization: aerius-labs
          github-repo: athena
          git-ref: master
          chain: athena
          dockerfile: cosmos
          tag: latest
          build-target: go build -tags=muslc -ldflags "$LDFLAGS" -o build/athena ./cmd/athenad
          build-env: |
            - CGO_ENABLED=1
          binaries: |
            - build/athena